name: Publish npm package

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Select type of version increment'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

run-name: "[${{ github.ref == 'refs/heads/main' && inputs.version || 'patch' }}] - Commit message '${{ github.event.head_commit.message }}'"

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_OPTIONS: '--max_old_space_size=4096'
  DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}

jobs:
  build-publish:
    runs-on: ubuntu-latest
    name: Publish npm package UI
    if: "!contains(github.event.head_commit.message, '[skip]')"

    steps:
      - name: Checkout code ğŸ“
        uses: actions/checkout@v3

      - name: Add credentials ğŸ”’
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc

      - name: Install Deno â¬‡ï¸
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install dependencies â¬‡ï¸
        run: npm ci

      - name: Build âš’ï¸
        run: npm run build

      - name; Test ğŸ§ª
        run: npm run test

      - name: Preview ğŸ‘€
        run: npm run preview & sleep 1 && kill $!

      - name: Publish ğŸš€
        run: |
          npm version ${{ github.ref == 'refs/heads/main' && inputs.version || 'patch' }} -m "Version %s by ${{ github.actor }}"
          npm publish
          git push
